### ISSUE TITLE
What is the license for the code? Is it MIT?

### ISSUE THREAD

**Issue by rmacfadyen** [raminrahimzada/CSharp-Helper-Classes#10]
I was wondering what license this code is provided under? MIT would be a great choice :)

Thanks!

**Comment by raminrahimzada** [comment]
Hi @rmacfadyen 
Sorry for late response, I did not notice this
Sure, You can use any of the parts in any case,
I dont want to set licence to all of the repo because I copied few lines of codes from different sources
But almost all is mine and you can use it without blaming me future bugs that may break your prod :)
If this statements mirror the MIT license then- yeah it is MIT licencesed.

**Comment by rmacfadyen** [comment]
Thx!
